server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:hbys
    username: hbystetkik
    password: hbys123
  jpa:
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
