server:
  port: 9090
#  servlet-path: /rest/*
  tomcat:
    uri-encoding: UTF-8


spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:hbys
#    username: hbystetkik
#    password: hbys123
  datasource:
      url: jdbc:mysql://localhost:3306/hbys
      username: hbystetkik
      password: hbys123
  jpa:
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        dialect:  org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy


